// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpzzfgSiSRnpaq4aegLZrPm-9PIhDeTgU',
    appId: '1:986627143600:web:b9280069ec58572b98c875',
    messagingSenderId: '986627143600',
    projectId: 'musicquizz-88140',
    authDomain: 'musicquizz-88140.firebaseapp.com',
    storageBucket: 'musicquizz-88140.appspot.com',
    measurementId: 'G-QE2CGQV6EQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqLYkYKJrVoNkAfMWFf_89D7DsZoOXakA',
    appId: '1:986627143600:android:ed7d14f72886bdc398c875',
    messagingSenderId: '986627143600',
    projectId: 'musicquizz-88140',
    storageBucket: 'musicquizz-88140.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp1LFHCjjGY7ZmBOXE2prnBt6fAq9te1M',
    appId: '1:986627143600:ios:27ae8dc671fce7fb98c875',
    messagingSenderId: '986627143600',
    projectId: 'musicquizz-88140',
    storageBucket: 'musicquizz-88140.appspot.com',
    iosClientId: '986627143600-k3nol0up32c7dabitj1k0115cb991d6e.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicQuizz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp1LFHCjjGY7ZmBOXE2prnBt6fAq9te1M',
    appId: '1:986627143600:ios:27ae8dc671fce7fb98c875',
    messagingSenderId: '986627143600',
    projectId: 'musicquizz-88140',
    storageBucket: 'musicquizz-88140.appspot.com',
    iosClientId: '986627143600-k3nol0up32c7dabitj1k0115cb991d6e.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicQuizz',
  );
}
